window.addEventListener("load", function(){

  var body = document.getElementsByTagName("body")[0];
  var docFrag = document.createDocumentFragment();
  var box = crear("div", "caja-1");

  var header = crear("header", "header");
  var divLeft = crear("div", "header-left");
  var spanLogoL = crear("span", "home icon-home3");
  var imgL = crear("div", "foto");
  var spanTw = crear("span", "enlace icon-twitter");
  var spanFc = crear("span", "enlace icon-facebook-with-circle");
  var divRight = crear("div", "header-right");
  var spanLogo = crear("img", "logo");
  var img = crear("img", "foto-autor");
  var spanSearch = crear("span","search icon-search");
  var spanEdit = crear("span", "edit");
  spanEdit.textContent = "Edit";
  var content = crear("section", "container");
  var divAutor = crear("div", "autor");
  var imgAutor = crear("img", "foto-autor img-autor");
  var divInfo = crear("div", "autor-info");
  var h5 = crear("h4", "name");
  h5.textContent = "Belen Recabal";
  var p1 = crear("p", "cv");
  p1.textContent = "Teaching Assistant at Laboratoria. Trabajando para ver màs mujeres en el mundo de la programaciòn.";
  var p2 = crear("p", "date");
  p2.textContent = "Mar 21 - 6 min read";
  var divContent = crear("div", "contenido");
  var h1 = crear("h1","titulo");
  h1.textContent = "Hazlo con estilo : Tipografìas, iconos y sprite";
  var pCont = crear("span", "informacion");
  pCont.textContent = "Te imaginas el mundo sin tipos de letra, tamaños, colores, o sin iconos , nada, nada sería iguaaaaaal!!!! Pero gracias a muchos desarrolladores y diseñadores, hoy contamos con una inimaginable gama de fuentes para nuestro desarrollos web, pero la pregunta que nos hacemos es, ";
  var sCont = crear("span", "cursiva informacion");
  sCont.textContent = "¿existen reglas, hay una mejor forma de hacerlo, no sé que tipografía usar?";
  var s2Cont = crear("span", "informacion");
  s2Cont.textContent = "Tengo muchas preguntas y pocas respuestas!!";
  var footer = crear("footer", "footer");
  var divBottonLeft = crear("div", "footLeft");
  var spanShare =crear("span","share icon-heart");
  var spanComment = crear("span", "comment icon-bubble2");
  var divBottonRight = crear("div", "footRight");
  var spanFavorite =crear("span","favorite tw icon-bookmark");
  var spanFace =crear("span","face icon-social-facebook-circular");
  var spanTiw =crear("span"," tw enlace icon-twitter");

  divLeft.appendChild(spanLogoL);
  divLeft.appendChild(imgL);
  divLeft.appendChild(spanTw);
  divLeft.appendChild(spanFc);
  divRight.appendChild(spanEdit);
  divRight.appendChild(spanSearch);
  divRight.appendChild(img);
  divRight.appendChild(spanLogo);
  header.appendChild(divLeft);
  header.appendChild(divRight);
  divInfo.appendChild(h5);
  divInfo.appendChild(p1);
  divInfo.appendChild(p2);
  divAutor.appendChild(imgAutor);
  divAutor.appendChild(divInfo);
  divContent.appendChild(h1);
  divContent.appendChild(pCont);
  divContent.appendChild(sCont);
  divContent.appendChild(s2Cont);
  content.appendChild(divAutor);
  content.appendChild(divContent);
  divBottonLeft.appendChild(spanShare);
  divBottonLeft.appendChild(spanComment);
  divBottonRight.appendChild(spanTiw);
  divBottonRight.appendChild(spanFace);
  divBottonRight.appendChild(spanFavorite);
  footer.appendChild(divBottonLeft);
  footer.appendChild(divBottonRight);
  box.appendChild(header);
  box.appendChild(content);
  box.appendChild(footer);


  docFrag.appendChild(box);
  body.insertBefore(docFrag, body.childNodes[0]);
});
